description: >
  CircleCI's Ubuntu-based machine executor VM:
  https://circleci.com/docs/2.0/executor-types/#using-machine
parameters:
  image:
    type: string
    default: vvakame/review:3.1

docker:
  - image: <<parameters.image>>
